class PopulaPaisesComGentilico < ActiveRecord::Migration
  def self.up
    Pais.create(:nome => "Brasil", :gentilico => "Brasileiro", :gentilico_feminino => "Brasileira")
    Pais.create(:nome => "Afeganistão", :gentilico => "Afegão", :gentilico_feminino => "Afegã")
    Pais.create(:nome => "África do Sul", :gentilico => "Sul-africano", :gentilico_feminino => "Sul-africana")
    Pais.create(:nome => "Albânia", :gentilico => "Albanês", :gentilico_feminino => "Albanesa")
    Pais.create(:nome => "Alemanha", :gentilico => "Alemão", :gentilico_feminino => "Alemã")
    Pais.create(:nome => "Andorra", :gentilico => "Andorrano", :gentilico_feminino => "Andorrana")
    Pais.create(:nome => "Angola", :gentilico => "Angolano", :gentilico_feminino => "Angolana")
    Pais.create(:nome => "Angula", :gentilico => "Angulano", :gentilico_feminino => "Angulana")
    Pais.create(:nome => "Antártida", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Antígua e Barbuda", :gentilico => "Antiguano", :gentilico_feminino => "Antiguana")
    Pais.create(:nome => "Antilhas Holandesas", :gentilico => "Antilhano", :gentilico_feminino => "Antilhana")
    Pais.create(:nome => "Arábia Saudita", :gentilico => "Saudita", :gentilico_feminino => "Saudita")
    Pais.create(:nome => "Argélia", :gentilico => "Argelino", :gentilico_feminino => "Argelina")
    Pais.create(:nome => "Argentina", :gentilico => "Argentino", :gentilico_feminino => "Argentina")
    Pais.create(:nome => "Armênia", :gentilico => "Armênio", :gentilico_feminino => "Armênia")
    Pais.create(:nome => "Aruba", :gentilico => "Arubano", :gentilico_feminino => "Arubana")
    Pais.create(:nome => "Austrália", :gentilico => "Australiano", :gentilico_feminino => "Australiana")
    Pais.create(:nome => "Áustria", :gentilico => "Austríaco", :gentilico_feminino => "Austríaca")
    Pais.create(:nome => "Azerbaijão", :gentilico => "Azerbaijano", :gentilico_feminino => "Azerbaijana")
    Pais.create(:nome => "Bahamas", :gentilico => "Bahamense", :gentilico_feminino => "Bahamense")
    Pais.create(:nome => "Bahrain", :gentilico => "Bahrainita", :gentilico_feminino => "Bahrainita")
    Pais.create(:nome => "Bangladesh", :gentilico => "Bengali", :gentilico_feminino => "Bengali")
    Pais.create(:nome => "Barbados", :gentilico => "Barbadiano", :gentilico_feminino => "Barbadiana")
    Pais.create(:nome => "Belarus", :gentilico => "Bielorrusso", :gentilico_feminino => "Bielorrussa")
    Pais.create(:nome => "Bélgica", :gentilico => "Belga", :gentilico_feminino => "Belga")
    Pais.create(:nome => "Belize", :gentilico => "Belizenho", :gentilico_feminino => "Belizenha")
    Pais.create(:nome => "Benin", :gentilico => "Beninense", :gentilico_feminino => "Beninense")
    Pais.create(:nome => "Bermuda", :gentilico => "Bermudenho", :gentilico_feminino => "Bermudenha")
    Pais.create(:nome => "Bolívia", :gentilico => "Boliviano", :gentilico_feminino => "Boliviana")
    Pais.create(:nome => "Bósnia e Herzegovina", :gentilico => "Bósnio", :gentilico_feminino => "Bósnia")
    Pais.create(:nome => "Botsuana", :gentilico => "Botsuano", :gentilico_feminino => "Botsuana")
    Pais.create(:nome => "Brunei", :gentilico => "Bruneano", :gentilico_feminino => "Bruneana")
    Pais.create(:nome => "Bulgária", :gentilico => "Búlgaro", :gentilico_feminino => "Búlgara")
    Pais.create(:nome => "Burkina Fasso", :gentilico => "Burquinense", :gentilico_feminino => "Burquinense")
    Pais.create(:nome => "Burundi", :gentilico => "Burundiano", :gentilico_feminino => "Burundiano")
    Pais.create(:nome => "Butão", :gentilico => "Butani", :gentilico_feminino => "Butani")
    Pais.create(:nome => "Cabo Verde", :gentilico => "Caboverdiano", :gentilico_feminino => "Caboverdiano")
    Pais.create(:nome => "Camarões", :gentilico => "Camaronês", :gentilico_feminino => "Camaronesa")
    Pais.create(:nome => "Camboja", :gentilico => "Cambojano", :gentilico_feminino => "Cambojana")
    Pais.create(:nome => "Canadá", :gentilico => "Canadense", :gentilico_feminino => "Canadense")
    Pais.create(:nome => "Catar", :gentilico => "Catarense", :gentilico_feminino => "Catarense")
    Pais.create(:nome => "Cazaquistão", :gentilico => "Cazaque", :gentilico_feminino => "Cazaque")
    Pais.create(:nome => "Chade", :gentilico => "Chadiense", :gentilico_feminino => "Chadiense")
    Pais.create(:nome => "Chile", :gentilico => "Chileno", :gentilico_feminino => "Chilena")
    Pais.create(:nome => "China", :gentilico => "Chines", :gentilico_feminino => "Chinesa")
    Pais.create(:nome => "Chipre", :gentilico => "Cipriota", :gentilico_feminino => "Cipriota")
    Pais.create(:nome => "Cidade do Vaticano", :gentilico => "Vaticano", :gentilico_feminino => "Vaticana")
    Pais.create(:nome => "Cingapura", :gentilico => "Cingapuriano", :gentilico_feminino => "Cingapuriano")
    Pais.create(:nome => "Colômbia", :gentilico => "Colombiano", :gentilico_feminino => "Colombiana")
    Pais.create(:nome => "Comores", :gentilico => "Comorense", :gentilico_feminino => "Comoriano")
    Pais.create(:nome => "Congo", :gentilico => "Congolês", :gentilico_feminino => "Congolesa")
    Pais.create(:nome => "Coréia do Sul", :gentilico => "Sul-coreano", :gentilico_feminino => "Sul-coreana")
    Pais.create(:nome => "Costa do Marfim", :gentilico => "Marfinense", :gentilico_feminino => "Marfinense")
    Pais.create(:nome => "Costa Rica", :gentilico => "Costarriquenho", :gentilico_feminino => "Costarriquenha")
    Pais.create(:nome => "Croácia", :gentilico => "Croata", :gentilico_feminino => "Croata")
    Pais.create(:nome => "Cuba", :gentilico => "Cubano", :gentilico_feminino => "Cubana")
    Pais.create(:nome => "Dinamarca", :gentilico => "Dinamarquês", :gentilico_feminino => "Dinamarquesa")
    Pais.create(:nome => "Djibuti", :gentilico => "Djibutiense", :gentilico_feminino => "Djibutiense")
    Pais.create(:nome => "Dominica", :gentilico => "Dominiquês", :gentilico_feminino => "Dominiquesa")
    Pais.create(:nome => "Egito", :gentilico => "Egípcio", :gentilico_feminino => "Egípcia")
    Pais.create(:nome => "El Salvador", :gentilico => "Salvadorenho", :gentilico_feminino => "Salvadorenha")
    Pais.create(:nome => "Emirados Árabes Unidos", :gentilico => "Árabe", :gentilico_feminino => "Árabe")
    Pais.create(:nome => "Equador", :gentilico => "Equatoriano", :gentilico_feminino => "Equatoriana")
    Pais.create(:nome => "Eritréia", :gentilico => "Eritréio", :gentilico_feminino => "Eritréia")
    Pais.create(:nome => "Eslováquia", :gentilico => "Eslovaco", :gentilico_feminino => "Eslovaca")
    Pais.create(:nome => "Eslovênia", :gentilico => "Esloveno", :gentilico_feminino => "Eslovena")
    Pais.create(:nome => "Espanha", :gentilico => "Espanhol", :gentilico_feminino => "Espanhola")
    Pais.create(:nome => "Estados Unidos", :gentilico => "Estadunidense", :gentilico_feminino => "Estadunidense")
    Pais.create(:nome => "Estônia", :gentilico => "Estoniano", :gentilico_feminino => "Estoniano")
    Pais.create(:nome => "Etiópia", :gentilico => "Etíope", :gentilico_feminino => "Etíope")
    Pais.create(:nome => "Fiji", :gentilico => "Fijiano", :gentilico_feminino => "Fijiana")
    Pais.create(:nome => "Filipinas", :gentilico => "Filipino", :gentilico_feminino => "Filipina")
    Pais.create(:nome => "Finlândia", :gentilico => "Finlandês", :gentilico_feminino => "Finlandesa")
    Pais.create(:nome => "França", :gentilico => "Francês", :gentilico_feminino => "Francesa")
    Pais.create(:nome => "Gabão", :gentilico => "Gabonês", :gentilico_feminino => "Gabonesa")
    Pais.create(:nome => "Gâmbia", :gentilico => "Gambiano", :gentilico_feminino => "Gambiana")
    Pais.create(:nome => "Gana", :gentilico => "Ganês", :gentilico_feminino => "Ganesa")
    Pais.create(:nome => "Geórgia", :gentilico => "Georgiano", :gentilico_feminino => "Georgiana")
    Pais.create(:nome => "Gibraltar", :gentilico => "Gibraltino", :gentilico_feminino => "Gibraltino")
    Pais.create(:nome => "Grécia", :gentilico => "Grego", :gentilico_feminino => "Grega")
    Pais.create(:nome => "Grenada", :gentilico => "Granadino", :gentilico_feminino => "Granadino")
    Pais.create(:nome => "Groenlândia", :gentilico => "Groenlandês", :gentilico_feminino => "Groenlandesa")
    Pais.create(:nome => "Guadalupe", :gentilico => "Guadalupano", :gentilico_feminino => "Guadalupano")
    Pais.create(:nome => "Guam", :gentilico => "Guamês", :gentilico_feminino => "Guamesa")
    Pais.create(:nome => "Guatemala", :gentilico => "Guatemalteco", :gentilico_feminino => "Guatemalteca")
    Pais.create(:nome => "Guiana", :gentilico => "Guianense", :gentilico_feminino => "Guianense")
    Pais.create(:nome => "Guiana Francesa", :gentilico => "Guianense", :gentilico_feminino => "Guianense")
    Pais.create(:nome => "Guiné", :gentilico => "Guineano", :gentilico_feminino => "Guineana")
    Pais.create(:nome => "Guiné Equatorial", :gentilico => "Guineu-equatoriano", :gentilico_feminino => "Guineu-equatoriana")
    Pais.create(:nome => "Guiné-Bissau", :gentilico => "Guineense", :gentilico_feminino => "Guineense")
    Pais.create(:nome => "Haiti", :gentilico => "Haitiano", :gentilico_feminino => "Haitiana")
    Pais.create(:nome => "Holanda", :gentilico => "Holandês", :gentilico_feminino => "Holandesa")
    Pais.create(:nome => "Honduras", :gentilico => "Hondurenho", :gentilico_feminino => "Hondurenha")
    Pais.create(:nome => "Hong Kong S. A. R", :gentilico => "honconguês", :gentilico_feminino => "honconguesa")
    Pais.create(:nome => "Hungria", :gentilico => "Húngaro", :gentilico_feminino => "Húngara")
    Pais.create(:nome => "Iêmen", :gentilico => "Iemenita", :gentilico_feminino => "Iemenita")
    Pais.create(:nome => "Ilha Bouvet", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Ilha Christmas", :gentilico => "Natalense", :gentilico_feminino => "Natalense")
    Pais.create(:nome => "Ilha Norfolk", :gentilico => "Norfolquino", :gentilico_feminino => "Norfolquina")
    Pais.create(:nome => "Ilhas Cayman", :gentilico => "Caimanês", :gentilico_feminino => "Caimanesa")
    Pais.create(:nome => "Ilhas Cocos (Keeling)", :gentilico => "Coquense", :gentilico_feminino => "Coquense")
    Pais.create(:nome => "Ilhas Cook", :gentilico => "Cookense", :gentilico_feminino => "Cookense")
    Pais.create(:nome => "Ilhas Faroés", :gentilico => "Faroense", :gentilico_feminino => "Faroense")
    Pais.create(:nome => "Ilhas Geórgia do Sul e Sandwich do Sul", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Ilhas Heard e Ilhas McDonald", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Ilhas Malvinas (Falkland)", :gentilico => "Malvino", :gentilico_feminino => "Malvina")
    Pais.create(:nome => "Ilhas Marianas do Norte", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Ilhas Marshall", :gentilico => "Marshallino", :gentilico_feminino => "Marshallino")
    Pais.create(:nome => "Ilhas Salomão", :gentilico => "Salomônico", :gentilico_feminino => "Salomônica")
    Pais.create(:nome => "Ilhas Turks e Caicos", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Ilhas Virgens Americanas", :gentilico => "Virginense", :gentilico_feminino => "Virginense")
    Pais.create(:nome => "Ilhas Virgens Britânicas", :gentilico => "Virginense", :gentilico_feminino => "Virginense")
    Pais.create(:nome => "Índia", :gentilico => "Indiano", :gentilico_feminino => "Indiana")
    Pais.create(:nome => "Indonésia", :gentilico => "Indonésio", :gentilico_feminino => "Indonésia")
    Pais.create(:nome => "Irã", :gentilico => "Iraniano", :gentilico_feminino => "Iraniana")
    Pais.create(:nome => "Iraque", :gentilico => "Iraquiano", :gentilico_feminino => "Iraquiana")
    Pais.create(:nome => "Irlanda", :gentilico => "Irlandês", :gentilico_feminino => "Irlandesa")
    Pais.create(:nome => "Islândia", :gentilico => "Islandês", :gentilico_feminino => "Islandesa")
    Pais.create(:nome => "Israel", :gentilico => "Israelense", :gentilico_feminino => "Israelense")
    Pais.create(:nome => "Itália", :gentilico => "Italiano", :gentilico_feminino => "Italiana")
    Pais.create(:nome => "Iugoslávia", :gentilico => "Iugoslavo", :gentilico_feminino => "Iugoslava")
    Pais.create(:nome => "Jamaica", :gentilico => "Jamaicano", :gentilico_feminino => "Jamaicana")
    Pais.create(:nome => "Japão", :gentilico => "Japonês", :gentilico_feminino => "Japonesa")
    Pais.create(:nome => "Jordânia", :gentilico => "Jordaniano", :gentilico_feminino => "Jordaniana")
    Pais.create(:nome => "Kiribati", :gentilico => "Quiribatiano", :gentilico_feminino => "Quiribatiano")
    Pais.create(:nome => "Kuwait", :gentilico => "Kuwaitiano", :gentilico_feminino => "Kuwaitiano")
    Pais.create(:nome => "Laos", :gentilico => "Laosiano", :gentilico_feminino => "Laosiano")
    Pais.create(:nome => "Lesoto", :gentilico => "Lesotiano", :gentilico_feminino => "Lesotiano")
    Pais.create(:nome => "Letônia", :gentilico => "Letão", :gentilico_feminino => "Letã")
    Pais.create(:nome => "Líbano", :gentilico => "Libanês", :gentilico_feminino => "Libanesa")
    Pais.create(:nome => "Libéria", :gentilico => "Liberiano", :gentilico_feminino => "Liberiana")
    Pais.create(:nome => "Líbia", :gentilico => "Líbio", :gentilico_feminino => "Líbia")
    Pais.create(:nome => "Liechtenstein", :gentilico => "Liechtensteinense", :gentilico_feminino => "Liechtensteinense")
    Pais.create(:nome => "Lituânia", :gentilico => "Lituano", :gentilico_feminino => "Lituana")
    Pais.create(:nome => "Luxemburgo", :gentilico => "Luxemburguês", :gentilico_feminino => "Luxemburguesa")
    Pais.create(:nome => "Macau S.A.R.", :gentilico => "Macaense", :gentilico_feminino => "Macaense")
    Pais.create(:nome => "Madagascar", :gentilico => "Malgaxe", :gentilico_feminino => "Malgaxe")
    Pais.create(:nome => "Malásia", :gentilico => "Malaio", :gentilico_feminino => "Malaia")
    Pais.create(:nome => "Malaui", :gentilico => "Malauita", :gentilico_feminino => "Malauita")
    Pais.create(:nome => "Maldivas", :gentilico => "Maldívio", :gentilico_feminino => "Maldívia")
    Pais.create(:nome => "Mali", :gentilico => "Malinês", :gentilico_feminino => "Malinesa")
    Pais.create(:nome => "Malta", :gentilico => "Maltês", :gentilico_feminino => "Maltesa")
    Pais.create(:nome => "Marrocos", :gentilico => "Marroquino", :gentilico_feminino => "Marroquina")
    Pais.create(:nome => "Martinica", :gentilico => "Martinicano", :gentilico_feminino => "Martinicana")
    Pais.create(:nome => "Maurício", :gentilico => "Mauriciano", :gentilico_feminino => "Mauriciana")
    Pais.create(:nome => "Mauritânia", :gentilico => "Mauritano", :gentilico_feminino => "Mauritana")
    Pais.create(:nome => "Mayotte", :gentilico => "Maiotense", :gentilico_feminino => "Maiotense")
    Pais.create(:nome => "México", :gentilico => "Mexicano", :gentilico_feminino => "Mexicana")
    Pais.create(:nome => "Micronésia", :gentilico => "Micronésio", :gentilico_feminino => "Micronésia")
    Pais.create(:nome => "Moçambique", :gentilico => "Mocambicano", :gentilico_feminino => "Mocambicana")
    Pais.create(:nome => "Moldávia", :gentilico => "Moldavo", :gentilico_feminino => "Moldava")
    Pais.create(:nome => "Mônaco", :gentilico => "Monegasco", :gentilico_feminino => "Monegasca")
    Pais.create(:nome => "Mongólia", :gentilico => "Mongol", :gentilico_feminino => "Mongol")
    Pais.create(:nome => "Montserrat", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Myanmar", :gentilico => "Myanmarense", :gentilico_feminino => "Myanmarense")
    Pais.create(:nome => "Namíbia", :gentilico => "Namibiano", :gentilico_feminino => "Namibiana")
    Pais.create(:nome => "Nauru", :gentilico => "Nauruano", :gentilico_feminino => "Nauruana")
    Pais.create(:nome => "Nepal", :gentilico => "Nepalês", :gentilico_feminino => "Nepalesa")
    Pais.create(:nome => "Nicarágua", :gentilico => "Nicaraguense", :gentilico_feminino => "Nicaraguense")
    Pais.create(:nome => "Níger", :gentilico => "Nigerino", :gentilico_feminino => "Nigerina")
    Pais.create(:nome => "Nigéria", :gentilico => "Nigeriano", :gentilico_feminino => "Nigeriana")
    Pais.create(:nome => "Ninive", :gentilico => "Ninivita", :gentilico_feminino => "Ninivita")
    Pais.create(:nome => "Noruega", :gentilico => "Norueguês", :gentilico_feminino => "Norueguesa")
    Pais.create(:nome => "Nova Caledônia", :gentilico => "Neocaledônio", :gentilico_feminino => "Neocaledônia")
    Pais.create(:nome => "Nova Zelândia", :gentilico => "Neozelandes", :gentilico_feminino => "Neozelandesa")
    Pais.create(:nome => "Omã", :gentilico => "Omani", :gentilico_feminino => "Omani")
    Pais.create(:nome => "Palau", :gentilico => "Palauense", :gentilico_feminino => "Palauense")
    Pais.create(:nome => "Panamá", :gentilico => "Panamenho", :gentilico_feminino => "Panamenha")
    Pais.create(:nome => "Papua-Nova Guiné", :gentilico => "Papuásio", :gentilico_feminino => "Papuásia")
    Pais.create(:nome => "Paquistão", :gentilico => "Paquistanes", :gentilico_feminino => "Paquistanesa")
    Pais.create(:nome => "Paraguai", :gentilico => "Paraguaio", :gentilico_feminino => "Paraguaia")
    Pais.create(:nome => "Peru", :gentilico => "Peruano", :gentilico_feminino => "Peruana")
    Pais.create(:nome => "Pitcairn", :gentilico => "Pitcairnense", :gentilico_feminino => "Pitcairnense")
    Pais.create(:nome => "Polinésia Francesa", :gentilico => "Polinésio", :gentilico_feminino => "Polinésia")
    Pais.create(:nome => "Polônia", :gentilico => "Polonês", :gentilico_feminino => "Polonesa")
    Pais.create(:nome => "Porto Rico", :gentilico => "Portorriquenho", :gentilico_feminino => "Portorriquenha")
    Pais.create(:nome => "Portugal", :gentilico => "Português", :gentilico_feminino => "Portuguesa")
    Pais.create(:nome => "Quênia", :gentilico => "Queniano", :gentilico_feminino => "Queniana")
    Pais.create(:nome => "Quirguistão", :gentilico => "Quirguiz", :gentilico_feminino => "Quirquiza")
    Pais.create(:nome => "Reino Unido", :gentilico => "Inglês", :gentilico_feminino => "Inglesa")
    Pais.create(:nome => "República Centro-Africana", :gentilico => "Centro-africano", :gentilico_feminino => "Centro-africana")
    Pais.create(:nome => "Macedônia", :gentilico => "Macedônio", :gentilico_feminino => "Macedônia")
    Pais.create(:nome => "República Dominicana", :gentilico => "Dominicano", :gentilico_feminino => "Dominicana")
    Pais.create(:nome => "República Tcheca", :gentilico => "Tcheco", :gentilico_feminino => "Tcheca")
    Pais.create(:nome => "Reunião", :gentilico => "Reunionense", :gentilico_feminino => "Reunionense")
    Pais.create(:nome => "Romênia", :gentilico => "Romeno", :gentilico_feminino => "Romena")
    Pais.create(:nome => "Ruanda", :gentilico => "Ruandês", :gentilico_feminino => "Ruandesa")
    Pais.create(:nome => "Rússia", :gentilico => "Russo", :gentilico_feminino => "Russa")
    Pais.create(:nome => "Saint-Pierre e Miquelon", :gentilico => "Pedro-miquelonense", :gentilico_feminino => "Pedro-miquelonense")
    Pais.create(:nome => "Samoa", :gentilico => "Samoano", :gentilico_feminino => "Samoana")
    Pais.create(:nome => "Samoa Americana", :gentilico => "Samoano", :gentilico_feminino => "Samoana")
    Pais.create(:nome => "San Marino", :gentilico => "Samarinês", :gentilico_feminino => "Samarinesa")
    Pais.create(:nome => "Santa Helena", :gentilico => "Santa-helenense", :gentilico_feminino => "Santa-helenense")
    Pais.create(:nome => "Santa Lúcia", :gentilico => "Santa-lucense", :gentilico_feminino => "Santa-lucense")
    Pais.create(:nome => "São Tomé e Príncipe", :gentilico => "Santomense", :gentilico_feminino => "Santomense")
    Pais.create(:nome => "São Vicente e Granadinas", :gentilico => "Sao-vicentino", :gentilico_feminino => "Sao-vicentina")
    Pais.create(:nome => "Senegal", :gentilico => "Senegalês", :gentilico_feminino => "Senegalesa")
    Pais.create(:nome => "Serra Leoa", :gentilico => "Serra-leonês", :gentilico_feminino => "Serra-leonesa")
    Pais.create(:nome => "Seychelles", :gentilico => "Seichelense", :gentilico_feminino => "Seichelense")
    Pais.create(:nome => "Síria", :gentilico => "Sírio", :gentilico_feminino => "Síria")
    Pais.create(:nome => "Somália", :gentilico => "Somali", :gentilico_feminino => "Somali")
    Pais.create(:nome => "Sri Lanka", :gentilico => "Cingalês", :gentilico_feminino => "Cingales")
    Pais.create(:nome => "St. Kitts e Névis", :gentilico => "Cristovo-nevense", :gentilico_feminino => "Cristovo-nevense")
    Pais.create(:nome => "Suazilândia", :gentilico => "Suazi", :gentilico_feminino => "Suazi")
    Pais.create(:nome => "Sudão", :gentilico => "Sudanês", :gentilico_feminino => "Sudanesa")
    Pais.create(:nome => "Suécia", :gentilico => "Sueco", :gentilico_feminino => "Sueca")
    Pais.create(:nome => "Suíça", :gentilico => "Suíço", :gentilico_feminino => "Suíça")
    Pais.create(:nome => "Suriname", :gentilico => "Surinamês", :gentilico_feminino => "Surinamesa")
    Pais.create(:nome => "Svalbard", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Tadjiquistão", :gentilico => "Tadjique", :gentilico_feminino => "Tadjique")
    Pais.create(:nome => "Tailândia", :gentilico => "Tailandês", :gentilico_feminino => "Tailandesa")
    Pais.create(:nome => "Taiwan", :gentilico => "Taiwanês", :gentilico_feminino => "Taiwanesa")
    Pais.create(:nome => "Tanzânia", :gentilico => "Tanzaniano", :gentilico_feminino => "Tanzaniana")
    Pais.create(:nome => "Território Britânico do Oceano Índico", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Territórios Franceses do Sul", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Territórios Insulares dos EUA", :gentilico => nil, :gentilico_feminino => nil)
    Pais.create(:nome => "Timor Leste", :gentilico => "Timorense", :gentilico_feminino => "Timorense")
    Pais.create(:nome => "Togo", :gentilico => "Togolês", :gentilico_feminino => "Togolesa")
    Pais.create(:nome => "Tokelau", :gentilico => "Toquelauense", :gentilico_feminino => "Toquelauense")
    Pais.create(:nome => "Tonga", :gentilico => "Tonganês", :gentilico_feminino => "Tonganesa")
    Pais.create(:nome => "Trinidad e Tobago", :gentilico => "Trinitário-tobagense", :gentilico_feminino => "Trinitário-tobagense")
    Pais.create(:nome => "Tunísia", :gentilico => "Tunisiano", :gentilico_feminino => "Tunisiana")
    Pais.create(:nome => "Turcomenistão", :gentilico => "Turcomeno", :gentilico_feminino => "Turcomeno")
    Pais.create(:nome => "Turquia", :gentilico => "Turco", :gentilico_feminino => "Turca")
    Pais.create(:nome => "Tuvalu", :gentilico => "Tuvaluano", :gentilico_feminino => "Tuvaluana")
    Pais.create(:nome => "Ucrânia", :gentilico => "Ucraniano", :gentilico_feminino => "Ucraniana")
    Pais.create(:nome => "Uganda", :gentilico => "Ugandês", :gentilico_feminino => "Ugandesa")
    Pais.create(:nome => "Uruguai", :gentilico => "Uruguiaio", :gentilico_feminino => "Uruguaia")
    Pais.create(:nome => "Uzbequistão", :gentilico => "Uzbeque", :gentilico_feminino => "Uzbeque")
    Pais.create(:nome => "Vanuatu", :gentilico => "Vanuatense", :gentilico_feminino => "Vanuatense")
    Pais.create(:nome => "Venezuela", :gentilico => "Venezuelano", :gentilico_feminino => "Venezuelana")
    Pais.create(:nome => "Vietnã", :gentilico => "Vietnamita", :gentilico_feminino => "Vietnamita")
    Pais.create(:nome => "Wallis e Futuna", :gentilico => "Wallis-futunense", :gentilico_feminino => "Wallis-futunense")
    Pais.create(:nome => "Zâmbia", :gentilico => "Zâmbio", :gentilico_feminino => "Zambiana")
    Pais.create(:nome => "Zimbábue", :gentilico => "Zimbabuano", :gentilico_feminino => "Zimbabuana")
  end

  def self.down
    Pais.delete_all
  end
end



